### ISSUE TITLE
Toggle key for horizontal scrolling doesn't work on Mojave

### ISSUE THREAD

**Issue by kkitay** [Caldis/Mos#125]
**Describe the bug | 问题描述**
I added "Shift" toggle key to change to horizontal scrolling. But it does not work at all, just continues vertical scrolling. In fact none of the toggle keys options work

**To Reproduce | 如何重现**
try it out on Mojave.

**Expected behavior | 期望结果**
holding shown shift and scrolling should scroll left/right

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [e.g. iOS] Mac OS Mojave 10.14.12
-  Application [e.g. Safari, Chrome, Whole System] Whole system

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Hi @kkitay , sorry i'm late, thank you for your feedback !

If the entire scrolling process is transformed, then you need to wait for the scroll to end before you can scroll in the other direction. Some users prefer longer animation delays, which can be very annoying.
In this case, I prefer to hold the transition key to take effect, instead of transform the entire scrolling process, it will make the reaction more immediate.

**Comment by kkitay** [comment]
hi caldis, thanks for the reply
so, the Shift + Scroll actually doesn't work at all for me on my work computer (also Mojave).
