### ISSUE TITLE
版本 3.0.0 公开测试

### ISSUE THREAD

**Issue by Caldis** [Caldis/Mos#206]
## 新版本已经发布, 请直接下载新版本即可使用.
   
https://github.com/Caldis/Mos/releases

---

<details>
  <summary>过期内容</summary>

# 恭喜

你找到了这里

### 为什么在这里发布 ?

我相信能找到这里的用户都具有不一般的探索精神, 我们十分欢迎您参与测试

实际上, 如果你留意过代码记录, 应该能发现 3.0.0 的代码其实早已就绪, 只是由于各种问题没有发布

由于这个版本间隔~~鸽~~了太久, 涉及多个配置项的变更, 加之 10.15 需求的 Notarizing 新限制, 造成了更麻烦的问题

### 我需要留意什么 ?

实际上, 新功能并不是本次测试的关注点 (不过你也可以在下面反馈), 我们更关注的是以下几个问题

- 由于配置项有较大变更, 如果你在运行过程中遭遇了错误, 请在下方反馈

- 由于 Apple 在最新版本中添加了应用程序发布前的公证(Notarizing) 要求, 但通过公证要求开发者加入 Developer Program **($99)**

很明显, 该编译版本没有经过 Notarizing, 如果你在执行前遇到了任何问题, 欢迎在下方反馈

如果在双击图标后没有反应, 你可以尝试以下的方法

```
右键点击应用程序, 选择 打开
将辅助功能中 Mos 的选项删除
弹出 无法验证..., 在 设置-安全性与隐私-通用 中允许运行
```

实际上, 在我本地的测试过程中, 也遇到了类似的问题, 但遗憾的是, 并没有太好的解决方案, 如果你有相关建议, 也欢迎在下方反馈

如果使用了以上方法能成功运行, 也请在下方反馈, 我们会在一切就绪后尽快发布正式版本

感谢参与测试

> [请点击此处下载测试版本](https://raw.githubusercontent.com/Caldis/Mos/master/Release/Mos.Versions.3.0.0.dmg)
</details>

**Comment by cattyhouse** [comment]
404? please fix the link

**Comment by Caldis** [comment]
@cattyhouse 太快了朋友...才上传完

**Comment by cattyhouse** [comment]
> @cattyhouse 太快了朋友...才上传完

除了iterm2 有点异常, 其他都ok. 加到Exception 列表了.

**Comment by suxiaogang** [comment]
不知道作为开发者, 我这个bug是否有点"小众"... #213

**Comment by balthild** [comment]
在添加「运行中的应用程序」为例外时，选择比如 java 的非 .app 格式的程序会导致 Mos 直接崩溃退出

<img width="494" alt="图片" src="https://user-images.githubusercontent.com/2662758/71479190-54879600-282e-11ea-9096-91f14ae44933.png">

**Comment by luckyyyyy** [comment]
系统中的 scroll direction: natural 和软件中的 reveres scroll 一起勾选
会出现一定概率性的 第一次滚动方向错误的问题

现在我的做法是两个都取消了 这样不会了

**Comment by Caldis** [comment]
@balthild 谢谢反馈, 确实有这个问题

**Comment by luckyyyyy** [comment]
@Caldis 在我测试这半个月中 经常出现滚动一个方向时突然反方一个滚轮 然后又正常
我家里和公司都这样
虽然是同型号的鼠标，但是我觉得不太可能两个都坏了

目前我被迫回2.x版本

**Comment by cyea** [comment]
@Caldis chrome 网页如果出现小的滚动视窗，当鼠标在小的滚动视窗时触底时，就滚不动了，大视窗不会滚动

**Comment by luckyyyyy** [comment]
> @Caldis chrome 网页如果出现小的滚动视窗，当鼠标在小的滚动视窗时触底时，就滚不动了，大视窗不会滚动
有个BUG不知可否遇到过？我找了很久。

用chrome 同时按c+r刷新页面，同时滚动，页面上下都可以被拉出空白一大截。
用普通鼠标配合 mos 必现

已经定位是mos的问题，mm或者触控板，或者关闭mos就正常了


@Caldis

**Comment by luckyyyyy** [comment]
这个问题也从chrome 75~77其中一个版本开始出现，我已经受困扰很久。

感觉是橡皮筋效果没有阻断，一直处于这个模式下。

**Comment by lechie** [comment]
> > @Caldis chrome 网页如果出现小的滚动视窗，当鼠标在小的滚动视窗时触底时，就滚不动了，大视窗不会滚动
> > 有个BUG不知可否遇到过？我找了很久。
> 
> 用chrome 同时按c+r刷新页面，同时滚动，页面上下都可以被拉出空白一大截。
> 用普通鼠标配合 mos 必现
> 
> 已经定位是mos的问题，mm或者触控板，或者关闭mos就正常了
> 
> @Caldis

同样bug

**Comment by CavalloneChen** [comment]
![image](https://user-images.githubusercontent.com/28266566/86785071-cf125780-c094-11ea-9f02-30fad4c96315.png)

**Comment by kchiahui93** [comment]
滚轮突然失效，无法通过滚轮滑动。
重启后启动mos显示 软件无法打开

**Comment by the-eric-kwok** [comment]
现在Mos 3.0无法启动了，启动台点击没有反应，在终端里启动提示被杀
![截屏2020-07-07 下午10 48 26](https://user-images.githubusercontent.com/16463312/86799007-063c3500-c0a4-11ea-915b-8333c6837631.png)

**Comment by morooi** [comment]
同样突然遇到无法启动，卸载重装试过 2.3.0，2.4.0，3.0.0，均不可。
macOS Catalina 10.15.5

**Comment by Voring** [comment]
系统10.15.5，本来一直正常使用，今天开机后无法无法使用，软件无法打开

**Comment by intgyl** [comment]
我的现象跟楼上一样也是突然不能用，重启重装都不行，系统是10.15.5


默认	09:29:34.576071+0800	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "未能打开文件“PlugIns”，因为它不存在。" UserInfo={NSURL=PlugIns/ -- file:///Applications/Mos.app/Contents/, NSFilePath=/Applications/Mos.app/Contents/PlugIns, NSUnderlyingError=0x7fdf2372c5e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
默认	09:29:34.576116+0800	lsd	- 45683955: Checking whether application is managed at file:///Applications/Mos.app//com.caldis.Mos
默认	09:29:34.589229+0800	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "com.caldis.Mos"
    );
    isPlaceholder = 0;
}
默认	09:29:34.598640+0800	Dock	LAUNCHING:0x0-0x74074 Mos foreground=0 bringForward=0 seed=142 userActivityCount=0
默认	09:29:34.627635+0800	amfid	/Applications/Mos.app/Contents/MacOS/Mos signature not valid: -2147409652
默认	09:29:34.636908+0800	kernel	mac_vnode_check_signature: /Applications/Mos.app/Contents/MacOS/Mos: code signature validation failed fatally: When validating /Applications/Mos.app/Contents/MacOS/Mos:
  The code contains a Team ID, but validating its signature failed.
Please check your system log.
默认	09:29:34.636931+0800	kernel	proc 2078: load code signature error 4 for file "Mos"
默认	09:29:34.637809+0800	ReportCrash	Parsing corpse data for process Mos [pid 2078]
默认	09:29:35.154546+0800	ReportCrash	Saved crash report for Mos[2078] version ??? to Mos_2020-07-08-092935_iMac.crash
默认	09:29:35.161032+0800	ReportCrash	Removing excessive log: Mos_2020-07-08-091736_iMac.crash

**Comment by yinyihui1995** [comment]
同样无法打开，系统版本 10.15.5 (19F101)
crash文件内容
`Process:               Mos [767]
Path:                  /Applications/Mos.app/Contents/MacOS/Mos
Identifier:            Mos
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Mos [767]
User ID:               501

Date/Time:             2020-07-08 12:14:44.022 +0800
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        733742B6-EFAB-CBB8-63CD-171A1BCB3E90


Time Awake Since Boot: 150 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010a6df000-000000010a87f000 [ 1664K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000010f93a000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee5520c08
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010f93a000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10a6df000 -        0x10a87efff +??? (0) <A8B1C156-1AC4-3C4D-85EA-592BC3FE592D> (null)
       0x10f939000 -        0x10f9caeff +??? (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2115
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=2784K resident=0K(0%) swapped_out_or_unallocated=2784K(100%)
Writable regions: Total=8420K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8420K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             712K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         536K        2 
__TEXT                            2248K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             67.4M       13 

`

**Comment by yinyihui1995** [comment]
找到了一个暂时的解决办法：移除签名

`codesign --remove-signature /Applications/mos.app`

然后就能重新打开，需要重新授权即可使用

**Comment by morooi** [comment]
> codesign --remove-signature /Applications/mos.app

感谢，终于能用了

**Comment by dhliubj** [comment]
> > codesign --remove-signature /Applications/mos.app
> 
> 感谢，终于能用了

请问是如下图在终端允许吗？我没有成功，烦请赐教，谢谢🙏

![截屏2020-07-08 下午3.11.22.png](https://i.loli.net/2020/07/08/hb5cLQaAiy3porV.png)

**Comment by morooi** [comment]
> > > codesign --remove-signature /Applications/mos.app
> > 
> > 
> > 感谢，终于能用了
> 
> 请问是如下图在终端运行吗？我没有成功，烦请赐教，谢谢🙏
> 
> ![截屏2020-07-08 下午3.11.22.png](https://camo.githubusercontent.com/204ad1faa8a46927a8050b42fa9f98ddfb7f8fe9/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f30382f686235634c516141697933706f72562e706e67)

你这是 Big Sur 么？
我这里是 Catalina 10.15.5，按照 @yinyihui1995 提供的方法一次成功。
也是像你截图一样的方式运行的。不起作用就不太知道了

**Comment by dhliubj** [comment]
> > > > codesign --remove-signature /Applications/mos.app
> > > 
> > > 
> > > 感谢，终于能用了
> > 
> > 
> > 请问是如下图在终端运行吗？我没有成功，烦请赐教，谢谢🙏
> > ![截屏2020-07-08 下午3.11.22.png](https://camo.githubusercontent.com/204ad1faa8a46927a8050b42fa9f98ddfb7f8fe9/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f30382f686235634c516141697933706f72562e706e67)
> 
> 你这是 Big Sur 么？
> 我这里是 Catalina 10.15.5，按照 @yinyihui1995 提供的方法一次成功。
> 也是像你截图一样的方式运行的。不起作用就不太知道了

是的，macOS Big Sur 11.0 Beta 2.
我运行上述代码后，还是存在问题，如下图
![截屏2020-07-08 下午3.27.26.png](https://i.loli.net/2020/07/08/3jiV4nvzEUTwrAu.png)

**Comment by Caldis** [comment]
十分抱歉带来不便，请直接下载新的正式版本即可，3.0 测试用的 CodeSign 过期了
https://github.com/Caldis/Mos/issues/277

**Comment by the-eric-kwok** [comment]
终于正式发布啦！🎉🎉
