### ISSUE TITLE
Smooth scrolling is not working with Docked folders and Mos 3.x

### ISSUE THREAD

**Issue by idanmashaal** [Caldis/Mos#280]
**Describe the bug | 问题描述**
Smooth scrolling is not working with docked folders such as "Downloads", "Applications" or any docked folder

**To Reproduce | 如何重现**
Drag a folder to the Dock

**Expected behavior | 期望结果**
Smooth scrolling will work as expected

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
Logitech MX Vertical
macOS Catalina 10.15.5
not relevant
 - Version [e.g. v69]
Mos 3.1.0
 -  Application [e.g. Safari, Chrome, Whole System]
macOS Dock

**Additional context | 额外说明**
My Mac Mini has an external screen, if this helps.
Same issue was reported in the following GitHub issues 207 and 277:
https://github.com/Caldis/Mos/issues/207#issuecomment-637609118
https://github.com/Caldis/Mos/issues/277#issuecomment-655398787

**Comment by Caldis** [comment]
In order to block smooth scrolling in Launchpad in order to switch between pages normally, we used BundleID, the "com.apple.launchpad" to identify whether Launchpad is activated. 
This also caused the Dock to not be smoothed.

In fact, before 10.15, Launchpad did not have a separate BundleID but a separate Window, the "LPSpringboard", which allowed him to be independently identified, and now I have not found a better solution

Related:
https://github.com/Caldis/Mos/blob/master/Mos/ScrollCore/ScrollUtils.swift#L119

**Comment by idanmashaal** [comment]
@Caldis does this means that Finder and Launchpad at the moment cannot be smoothed ?

**Comment by Caldis** [comment]
@idanmashaal nope, just the Dock and Launchpad cannot be handled separately, Finder was fined

**Comment by idanmashaal** [comment]
Hi @Caldis I checked the [Smooze app](https://smooze.co/) (which I also have a license to) and that app can make the dock smooth.
I prefer Mos though, because the way it flows is much better.
Any idea how Smooze can make the dock and launchpad smooth?

**Comment by MHX792** [comment]
@idanmashaal have you found any solution for this? This is kind of bothering me. 

@Caldis any plans for fixing this?
