### ISSUE TITLE
In iTerm2, scrolling speeds don't change properly in mouse-enabled programs

### ISSUE THREAD

**Issue by easyaspi314** [Caldis/Mos#82]
- 问题描述 | Issue description:
iTerm2 doesn't change the scrolling speed properly in mouse-enabled terminal programs.

- 如何重现 | How to reproduce it:
In iTerm2, assuming you have Xcode installed, run the following:
```
$ /usr/bin/vim -c "set mouse=a" -c "set ruler" /usr/include/zlib.h
```
Technically, that last argument can be any file, but zlib.h is long enough to see the effect (~2000 lines).

Scroll up and down slowly while changing the "Step" and "Speed" Mos settings.
When you are done, type the following and hit enter to quit Vim:
```
:q
```

Do the same in the built-in Terminal and while, yes, the scrolling is too fast to understand, the percentage on the bottom of the screen increases and decreases from a full scroll on different settings, while iTerm's does not.

For example, on my MacBook5,2's trackpad with the broken High Sierra drivers (it is awkwardly fast), on 10.0/1.0/1.0 on an 80x24 terminal window, a slow scroll down gets me to 17%, while with 100.0/10.0/1.0, I get to the bottom of the file halfway.

On iTerm2, I get about the same percentage in both settings, which is about 25%.

- 期望结果 | What is expected:
The scrolling speed should increase and decrease as necessary, like in Terminal.app.

- 实际结果 | What is actually happening:
The scrolling speed has no major changes.

- 软件版本 | Application version:
Mos 2.2.6
iTerm2 3.1.6 (Beta channel)
Terminal 2.8.2

- 系统版本 | System version:
macOS 10.13.4
MacBook5,2 (via High Sierra Patcher). Trackpad is detected as a USB mouse but still works mostly.

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
Nothing that I know of.

**Comment by Caldis** [comment]
Hi @easyaspi314 , the suggestion is add the iTerm2 or Terminal to Exception list and disable the smooth scrolling of it to avoid the smoothing in those app.

The problem is, like the iTerm2 & Terminal, those command line application have one thing in common is those scrolling are base the line instead of pixel. You can easily noticed the text of line are never be cut off by the edge of application. 

Because the line based scrolling will ignoring the distance of scrolling, they just cared the number of scrolls.

In fact, you can see the process of Mos scrolling interpolation in Scrolling Monitor is, separate the single scrolling to tons of small and dense scrolling to make the scrolling smooth.

So the iTerm2 & Terminal will misunderstand the precessed scrolling, and turn it to the tons of line scrolling.
